spring.application.name=order

server.port=9082

payment.base-url=http://localhost:9080
payment.retry.maxAttempts=3
payment.retry.minBackoffMs=300
payment.retry.jitter.factor=0.5
payment.timeout.ms:600
